### PR TITLE
Standardization

### PR DESCRIPTION
**Pull request by karikarshivani**
### [Report](https://github.com/karikarshivani/InSpecReports/blob/master/Standardization/AWS_Foundations_CIS_Before.json) before changes
---
**Questions for @ejaronne:**
- [x] README - [model](https://github.com/CMSgov/cms-ars-3.1-moderate-red-hat-enterprise-linux-7-stig-overlay/blob/master/README.md)
  - ~~Should I remove other READMEs? html and txt?~~
  - ~~I've linked Github profiles for all the contributors, should I do this for other profiles?~~
  - ~~Should [this section](https://github.com/CMSgov/cms-ars-3.1-moderate-red-hat-enterprise-linux-7-stig-overlay/blob/master/README.md#different-run-options) be at the end of all the "Running This Overlay" sections?~~
  - ~~Replicated the Notices from the model, please lmk is they need to be updated~~
- [x] in inspec.yml, validate the title and the summary to be consistent
- [x] in inspec.yml, set `inspec_version: ">= 4.0"`
- [x] in inspec.yml, validate if any supports statements are valid at the overlay and baseline levels
  - ~~No support statements found~~
- [x] in inspec.yml, set path to url style
- [x] in inspec.yml, change from attributes to inputs
- [x] in inspec.yml, set `profile: ` for any inputs meant to override the baseline settings
- [x] in inspec.yml, set `sensitive: ` flags as appropriate, e.g., for user names, passwords, hostnames, etc.
- [x] in controls/, remove any instances of changes to the nist tag, and replace as needed according to the appropriate approach indicated in the [lifecycle SOP](https://saf.cms.gov/CMS_InSpec_Profile_Lifecycle_SOP_v1.0_20190702.pdf)
- [x] Update the License.md
---
### [Report](https://github.com/karikarshivani/InSpecReports/blob/master/Standardization/AWS_Foundations_CIS_After.json) after changes

### CODE REVIEW

**Comment by karikarshivani** [comment]
image

**Comment by ejaronne** [comment]
Should I remove other READMEs? html and txt? --- yes, please, leave only .md

I've linked Github profiles for all the contributors, should I do this for other profiles? --- yes, nice touch!

Should this section be at the end of all the "Running This Overlay" sections? - yes, thanks!

Replicated the Notices from the model, please lmk is they need to be updated -- talked with Aaron and realized that we needed additional notices, so I updated the README. Please see the 4 NOTICES as shown at the bottom of this (WIP, just look at the bottom NOTICES for now) template: https://github.com/mitre/docs-mitre-inspec/blob/master/templates/overlay_readme.md 

Please update the LICENSE to LICENSE.md with the content as shown here: https://github.com/CMSgov/cms-ars-3.1-moderate-red-hat-enterprise-linux-7-stig-overlay/blob/master/LICENSE.md. Also *remove* these lines from the README if present as they are redundant:
License
This project is dual-licensed under the terms of the Apache license 2.0 (apache-2.0)
This project is dual-licensed under the terms of the Creative Commons Attribution Share Alike 4.0 (cc-by-sa-4.0)

**Comment by ejaronne** [comment]
in inspec.yml, name and title should match the cms-ars3.1-aws-foundations-cis-baseline should match the overlay repo name

**Review by aaronlippold — CHANGES_REQUESTED** [review]
* The README and LICENSE file should not be an HTML doc they should be Markdown - unless this is the GHPages Files which should not be needed in the PR
* the CIS benchmark does not need to be attributed to the DISA STIGS only to the CIS Foundation
* The License.md file needed to have the references to the CIS specific license

**Comment by aaronlippold** [comment]
Remember there is a STIG variant of the LICENSE.md file and a CIS variant as well as a variant on the Notices - Please see the various repos for examples.

**Pull request merged**
